#!/usr/bin/env python3
"""Assemble .astro/warehouse.md from the psql metadata dumps."""
import os, re, sys, datetime, collections

OUT = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("WH_DUMP_DIR", ".")
DEST = sys.argv[2] if len(sys.argv) > 2 else ".astro/warehouse.md"
DATE = os.environ.get("WH_DATE", datetime.date.today().isoformat())

def rows(name, n):
    res = []
    p = os.path.join(OUT, name)
    if not os.path.exists(p):
        return res
    for line in open(p, encoding="utf-8"):
        line = line.rstrip("\n")
        if not line.strip():
            continue
        parts = line.split("|")
        if len(parts) < n:
            parts += [""] * (n - len(parts))
        res.append(parts[:n])
    return res

def esc(s):
    return (s or "").replace("|", "/").replace("\n", " ").strip()

# ---------------------------------------------------------------- load
tables = rows("tables.psv", 6)                     # schema, name, kind, reltuples, size, comment
exact = {k: v for k, v in rows("exact_counts.psv", 2)}
cols = rows("columns.psv", 7)                      # sch, tbl, pos, col, type, nullable, comment
cons = rows("constraints.psv", 6)                  # sch, tbl, type, cols, ftable, fcols
sapdesc = {k: v for k, v in rows("sap_desc.psv", 2)}
sapkeys = {k: v for k, v in rows("sap_keys.psv", 2)}
sapfields = {k: v for k, v in rows("sap_fields.psv", 2)}
sapfk = rows("sap_fk.psv", 3)
uqidx = collections.defaultdict(list)
for sch, tbl, c in rows("uniq_idx.psv", 3):
    uqidx[(sch, tbl)].append(c)
ifskeys = {k: v for k, v in rows("ifs_keys.psv", 2)}
ifslabels = {k: v for k, v in rows("ifs_labels.psv", 2)}
cats = rows("categoricals2.psv", 5)
exports = rows("export_queries.psv", 6)            # cat, sch, tbl, display, desc, active
extracts = rows("extraction_queries.psv", 4)
domains = rows("domains.psv", 3)
dbinfo = rows("dbinfo.psv", 4)
DBNAME, PGVER, DBSIZE, DBHOST = (dbinfo[0] if dbinfo else ["?", "?", "?", "?"])

colmap = collections.defaultdict(list)
for sch, tbl, pos, col, typ, nul, cmt in cols:
    colmap[(sch, tbl)].append((int(pos), col, typ, nul, cmt))
for v in colmap.values():
    v.sort()

pk, uq, fk = {}, collections.defaultdict(list), []
for sch, tbl, ctype, ccols, ftab, fcols in cons:
    if ctype == "p":
        pk[(sch, tbl)] = ccols
    elif ctype == "u":
        uq[(sch, tbl)].append(ccols)
    elif ctype == "f":
        fk.append((f"{sch}.{tbl}", ccols, ftab, fcols))

meta = {}
for sch, name, kind, rel, size, cmt in tables:
    key = f"{sch}.{name}"
    if key in exact:
        n, exact_flag = int(exact[key]), True
    elif rel:
        n, exact_flag = int(float(rel)), False
    else:
        n, exact_flag = None, False
    meta[(sch, name)] = dict(kind=kind, rows=n, exact=exact_flag,
                             size=int(size or 0), comment=esc(cmt))

def fmt_rows(m):
    if m["kind"] in ("v", "m"):
        return "view"
    if m["rows"] is None:
        return "?"
    return f"{m['rows']:,}".replace(",", " ") + ("" if m["exact"] else " ~")

def fmt_size(b):
    for unit in ("B", "kB", "MB", "GB"):
        if b < 1024 or unit == "GB":
            return f"{b:.0f} {unit}" if unit == "B" else f"{b:.1f} {unit}"
        b /= 1024.0

def key_col(sch, tbl):
    """Best-known key, in decreasing order of authority."""
    if (sch, tbl) in pk:
        return pk[(sch, tbl)], "PK"
    if uq.get((sch, tbl)):
        return uq[(sch, tbl)][0], "unique"
    if uqidx.get((sch, tbl)):
        return uqidx[(sch, tbl)][0], "unique index"
    if sch == "raw_data" and tbl in sapkeys:
        return sapkeys[tbl], "SAP DDIC"
    if sch == "clean_data" and tbl in ifskeys:
        have = {c.lower() for _, c, _, _, _ in colmap.get((sch, tbl), [])}
        k = [c for c in ifskeys[tbl].split(",") if c in have]
        if k:
            return ",".join(k), "IFS spec"
    return "", ""

DATE_TYPES = ("timestamp", "date")
def date_col(sch, tbl):
    prefer = ("updated_at", "created_at", "date_maj", "erdat", "aedat", "budat", "bldat")
    have = {c.lower(): c for _, c, t, _, _ in colmap.get((sch, tbl), [])
            if any(t.startswith(d) for d in DATE_TYPES) or re.match(r"^(erdat|aedat|budat|bldat|laeda)$", c.lower())}
    for p in prefer:
        if p in have:
            return have[p]
    return next(iter(have.values()), "")

def describe(sch, tbl):
    m = meta[(sch, tbl)]
    if m["comment"]:
        return m["comment"]
    if sch == "raw_data" and tbl in sapdesc:
        return esc(sapdesc[tbl])
    return ""

L = []
w = L.append

# ---------------------------------------------------------------- header
n_tab = sum(1 for m in meta.values() if m["kind"] in ("r", "p"))
n_view = sum(1 for m in meta.values() if m["kind"] in ("v", "m"))
schemas = sorted({s for s, _ in meta})

w(f"# Warehouse Schema — `{DBNAME}`\n")
w(f"> Generated by `/astronomer-data:warehouse-init` on {DATE}. Edit freely to add business context.")
w("> Row counts marked `~` are planner estimates (`pg_class.reltuples`); unmarked counts are exact.\n")
w(f"**Connection** — {PGVER} on `{DBHOST}`, database `{DBNAME}` "
  f"(credentials in `.env`: `DB_USER` / `DB_PASSWORD`). Total size **{DBSIZE}**.\n")
w(f"**Inventory** — {len(schemas)} schemas, {n_tab} tables, {n_view} views.\n")
w("| Schema | Tables | Views | Role |")
w("|---|---|---|---|")
roles = {
    "raw_data": "SAP ECC extraction landing zone — **read only**, never write here",
    "clean_data": "IFS-shaped target layer (transformed tables + views) — what exports read",
    "public": "Platform tables: users, jobs, ETL config, SAP/IFS dictionaries, AI assistant",
    "snapshots": "Point-in-time copies taken before Maintenance reload/restore operations",
}
for s in schemas:
    t = sum(1 for (sc, _), m in meta.items() if sc == s and m["kind"] in ("r", "p"))
    v = sum(1 for (sc, _), m in meta.items() if sc == s and m["kind"] in ("v", "m"))
    w(f"| `{s}` | {t} | {v} | {roles.get(s,'')} |")
w("")

# ---------------------------------------------------------------- layers
w("## Data Layer Hierarchy\n")
w("Query downstream first: `clean_data` > `raw_data`.\n")
w("| Layer | Schema | Purpose |")
w("|---|---|---|")
w("| Export / IFS target | `clean_data.*` | Tables and views already shaped to the IFS spec. Exports (`public.etl_export_queries`) read only from here. |")
w("| Raw source | `raw_data.*` | Verbatim SAP ECC tables + SharePoint imports. Read-only source of truth; **never** UPDATE/DELETE. |")
w("| Platform | `public.*` | Application state, ETL configuration, data dictionaries, AI assistant history. |")
w("| Backup | `snapshots.*` | Automatic snapshots written before destructive Maintenance operations. |")
w("")

# ---------------------------------------------------------------- quick ref
w("## Quick Reference\n")
w("Concept → table mappings drawn from the export catalog (`public.etl_export_queries`).\n")
w("| Concept | Table | Key Column | Date Column* | Rows |")
w("|---|---|---|---|---|")
seen = set()
for cat, sch, tbl, disp, desc, active in sorted(exports, key=lambda r: (r[0].lower(), r[3].lower())):
    if (sch, tbl) not in meta or (sch, tbl) in seen:
        continue
    seen.add((sch, tbl))
    m = meta[(sch, tbl)]
    flag = "" if active == "t" else " *(inactive)*"
    w(f"| {esc(disp)}{flag} <br/>`{esc(cat)}` | `{sch}.{tbl}` | `{key_col(sch,tbl)[0] or '—'}` | "
      f"`{date_col(sch,tbl) or '—'}` | {fmt_rows(m)} |")
w("")
w("\\* *Date column is a heuristic pick — `updated_at`/`created_at` when present, otherwise the "
  "first date/timestamp column, which may be a business date rather than an ingestion date.*\n")
w("*To add or reword a concept here, edit `public.etl_export_queries` "
  "(`display_name` / `description` / `category`) and re-run the refresh script — "
  "editing this table by hand will be overwritten.*\n")

# ---------------------------------------------------------------- domain routing
w("## Keyword → Table Routing\n")
w("Used by the AI assistant's RAG retriever (`public.ai_domain_tables`). Also a good human index.\n")
w("| Domain | Keywords | Tables |")
w("|---|---|---|")
for dom, kw, tbls in domains:
    kw = kw.strip("[]")
    tbls = tbls.strip("[]")
    tl = [t.strip() for t in tbls.split(",") if t.strip()]
    shown = ", ".join(f"`{t}`" for t in tl[:12])
    if len(tl) > 12:
        shown += f" … (+{len(tl)-12})"
    w(f"| `{dom}` | {esc(kw)} | {shown} |")
w("")

# ---------------------------------------------------------------- categoricals
w("## Categorical Columns\n")
w("Value families observed in planner statistics (`pg_stats.most_common_vals`). "
  "Lists show the most common values, not necessarily every value.\n")
w("| Table | Column | Distinct | Observed values |")
w("|---|---|---|---|")
for sch, tbl, col, nd, vals in cats:
    v = esc(vals)
    if len(v) > 160:
        v = v[:157] + "…"
    w(f"| `{sch}.{tbl}` | `{col}` | {nd} | {v} |")
w("")

# ---------------------------------------------------------------- detailed schemas
def detailed_schema(sch, title, note=""):
    w(f"## `{sch}` Schema\n")
    if note:
        w(note + "\n")
    items = sorted([(s, t) for (s, t) in meta if s == sch], key=lambda x: x[1])
    w("| Object | Kind | Rows | Size | Description |")
    w("|---|---|---|---|---|")
    for s, t in items:
        m = meta[(s, t)]
        kind = {"r": "table", "p": "partitioned", "v": "view", "m": "matview"}[m["kind"]]
        d = describe(s, t)
        if len(d) > 110:
            d = d[:107] + "…"
        w(f"| [`{t}`](#{sch.replace('_','-')}-{t.replace('_','-').lower()}) | {kind} | {fmt_rows(m)} "
          f"| {fmt_size(m['size'])} | {d} |")
    w("")
    for s, t in items:
        m = meta[(s, t)]
        w(f"### {sch}.{t}\n")
        d = describe(s, t)
        if d:
            w(d + "\n")
        w("| # | Column | Type | Null | Description |")
        w("|---|---|---|---|---|")
        kc = set((key_col(s, t)[0] or "").split(","))
        for pos, col, typ, nul, cmt in colmap.get((s, t), []):
            mark = " 🔑" if col in kc else ""
            d = esc(cmt) or (esc(ifslabels.get(f"{t}.{col.lower()}", "")) if s == "clean_data" else "")
            w(f"| {pos} | `{col}`{mark} | {typ} | {'Y' if nul=='YES' else 'N'} | {d} |")
        w("")
        bits = [f"**Rows:** {fmt_rows(m)}", f"**Size:** {fmt_size(m['size'])}"]
        kcv, ksrc = key_col(s, t)
        if kcv:
            bits.append(f"**Key:** `{kcv}` _({ksrc})_")
        for u in uq.get((s, t), []):
            bits.append(f"**Unique:** `{u}`")
        if m["rows"] and m["rows"] > 1_000_000:
            bits.append("**⚠️ Large table — always filter**")
        w("- " + "\n- ".join(bits) + "\n")

detailed_schema("clean_data", "clean_data",
    "IFS target layer. These are the tables and views the export engine reads. "
    "Safe to rebuild from `raw_data` via the ETL modules and the `clean_data.load_*` procedures.")

detailed_schema("public", "public",
    "Platform schema: application state, ETL configuration, SAP/IFS data dictionaries "
    "and AI-assistant storage. The AI assistant's `sql_guard` whitelists this schema.")

# ---------------------------------------------------------------- raw_data compact
w("## `raw_data` Schema\n")
w("Verbatim SAP ECC 6.0 extractions plus SharePoint imports. **Read-only** — never `UPDATE`/`DELETE` here.\n")
w("Descriptions and key columns come from the SAP DDIC dictionary "
  "(`public.sap_table_properties` / `public.sap_table_fields`).\n")
w("Columns are listed compactly (`name:type`); full detail per column, including French field "
  "labels, is in `public.sap_table_fields`.\n")
raws = sorted([(s, t) for (s, t) in meta if s == "raw_data"], key=lambda x: x[1])
w("| Table | Rows | Size | SAP key | Description |")
w("|---|---|---|---|---|")
for s, t in raws:
    m = meta[(s, t)]
    d = describe(s, t)
    if len(d) > 90:
        d = d[:87] + "…"
    k = key_col(s, t)[0]
    if len(k) > 45:
        k = k[:42] + "…"
    w(f"| [`{t}`](#raw-data-{t.replace('_','-').lower()}) | {fmt_rows(m)} | {fmt_size(m['size'])} "
      f"| `{k or '—'}` | {d} |")
w("")
for s, t in raws:
    m = meta[(s, t)]
    w(f"### raw_data.{t}\n")
    d = describe(s, t)
    if d:
        w(d + "\n")
    bits = [f"**Rows:** {fmt_rows(m)}", f"**Size:** {fmt_size(m['size'])}"]
    kcv, ksrc = key_col(s, t)
    if kcv:
        bits.append(f"**Key:** `{kcv}` _({ksrc})_")
    if m["rows"] and m["rows"] > 1_000_000:
        bits.append("**⚠️ Large table — always filter**")
    w("- " + "\n- ".join(bits))
    cl = colmap.get((s, t), [])
    w(f"- **Columns ({len(cl)}):** " + ", ".join(f"`{c}`:{ty}" for _, c, ty, _, _ in cl))
    w("")

# ---------------------------------------------------------------- snapshots
w("## `snapshots` Schema\n")
w("Automatic point-in-time copies written before destructive Maintenance operations "
  "(`POST /api/v1/maintenance/reload`, restores). Naming: `s<N>_<source_schema>_<source_table>`.\n")
w("| Table | Rows | Size |")
w("|---|---|---|")
for s, t in sorted([(s, t) for (s, t) in meta if s == "snapshots"], key=lambda x: x[1]):
    m = meta[(s, t)]
    w(f"| `{t}` | {fmt_rows(m)} | {fmt_size(m['size'])} |")
w("")

# ---------------------------------------------------------------- relationships
w("## Relationships\n")
w("### Declared foreign keys (PostgreSQL)\n")
if fk:
    w("| Child | Column(s) | Parent | Column(s) |")
    w("|---|---|---|---|")
    for child, c, parent, p in sorted(fk):
        w(f"| `{child}` | `{c}` | `{parent}` | `{p}` |")
else:
    w("_None declared._")
w("")
w("### SAP DDIC check-table graph (`raw_data`)\n")
w(f"{len(sapfk)} field→check-table links are declared in `public.sap_table_fields.check_table` "
  "and exposed as the view `public.ai_table_relationships`. They are *not* enforced by PostgreSQL "
  "but are the correct join paths. Most-referenced targets:\n")
tgt = collections.Counter(t for _, _, t in sapfk)
w("| Referenced table | Incoming links | Description |")
w("|---|---|---|")
for t, n in tgt.most_common(25):
    w(f"| `raw_data.{t}` | {n} | {esc(sapdesc.get(t,''))[:80]} |")
w("")
w("Query the full graph with:\n")
w("```sql\nSELECT * FROM public.ai_table_relationships;\n```\n")

# ---------------------------------------------------------------- gotchas
_raw_objs = {t for (s_, t) in colmap if s_ == "raw_data"}
_tech = {c: {t for (s_, t), cl in colmap.items() if s_ == "raw_data"
             and any(cc == c for _, cc, _, _, _ in cl)}
         for c in ("mandt", "loevm", "lvorm", "loekz", "stblg")}
tech_counts = ", ".join(f"`{c}` on {len(v)}/{len(_raw_objs)}" for c, v in _tech.items())

w("## Query Gotchas\n")
w("- **Do not add SAP technical filters.** Project decision (2026-06-15): queries here run without "
  "`mandt` / `loevm` / `lvorm` / `loekz` / `stblg` predicates — the extraction already applied them. "
  "Most `raw_data` objects do not even have those columns "
  f"({tech_counts}), so such a predicate "
  "usually raises `42703 column ... does not exist`. `backend/services/sql_filters.py` strips them "
  "from AI-generated SQL before `sql_guard` for exactly this reason.\n")
w("- **`raw_data` is read-only.** Corrections belong in `clean_data` or in the mapping tables.\n")
w("- **`clean_data.maintenance_object` holds all four IH02 natures** in one table, discriminated by "
  "`object_type` (`FUNC_LOC`, `EQUIPMENT`, `ARTICLE`, `BOM_ITEM`); `parent_id` carries the tree and "
  "`ref_object_id` the article of a BOM line. Deletes are soft (`is_active = false`) — filter on it.\n")
w("- **Table names are lowercase** in PostgreSQL even though SAP writes them uppercase "
  "(`raw_data.lfa1`, not `raw_data.LFA1`).\n")
w("- **Row counts marked `~`** come from planner statistics and drift between `ANALYZE` runs.\n")

# ---------------------------------------------------------------- refresh
w("## Refreshing\n")
w("```bash\n./.astro/refresh_warehouse.sh      # re-dumps metadata via psql and rewrites this file\n```\n")
w("Regenerate after schema migrations (`migrations/`) or after a full SAP re-extraction.\n")
w("**This file is fully generated and is overwritten in place — it does not merge.** "
  "Business context you want to keep belongs either in the database itself "
  "(`COMMENT ON TABLE/COLUMN`, `public.etl_export_queries.description`, `public.ai_domain_tables`), "
  "which this generator picks up automatically, or in a separate hand-written file next to it.\n")

os.makedirs(os.path.dirname(DEST) or ".", exist_ok=True)
path = DEST
open(path, "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote", path, os.path.getsize(path), "bytes,", len(L), "lines")
