-- Script de création de la table IDENTITY_INVOICE_INFO
-- Basé sur la structure Oracle fournie, adapté pour PostgreSQL

CREATE TABLE IF NOT EXISTS clean_data.identity_invoice_info (
    COMPANY VARCHAR(20),
    IDENTITY VARCHAR(20),
    PARTY_TYPE VARCHAR(4000),
    PARTY_TYPE_DB VARCHAR(20),
    INVOICE_FEE VARCHAR(5),
    EXPIRE_DATE DATE,
    NATIONAL_BANK_CODE VARCHAR(20),
    GROUP_ID VARCHAR(20),
    DEF_AUTHORIZER VARCHAR(20),
    PAY_TERM_ID VARCHAR(20),
    DEF_VAT_CODE VARCHAR(20),
    ROUNDING_TAX_CODE VARCHAR(20),
    DEF_CURRENCY VARCHAR(3),
    PAYM_DEV_DAYS NUMERIC(20),
    IDENTITY_TYPE VARCHAR(4000),
    IDENTITY_TYPE_DB VARCHAR(20),
    VOTING_SHARE_PERCENTAGE VARCHAR(4000),
    VOTING_SHARE_PERCENTAGE_DB VARCHAR(20),
    DEF_PRELIMINARY_CODE VARCHAR(20),
    AUTOMATIC_INVOICE VARCHAR(1),
    PERCENT_TOLERANCE NUMERIC(20),
    AMOUNT_TOLERANCE NUMERIC(20),
    NCF_REFERENCE_CHECK VARCHAR(5),
    TAX_EXEMPT VARCHAR(5),
    TAX_EXEMPT_VALID_FROM DATE,
    TAX_EXEMPT_VALID_TO DATE,
    SECOND_TIN VARCHAR(5),
    REPORT_AND_WITHHOLD VARCHAR(4000),
    REPORT_AND_WITHHOLD_DB VARCHAR(20),
    SUPPLIER_TAX_OFFICE_ID VARCHAR(20),
    NUMERATION_GROUP VARCHAR(20),
    TAX_BOOK_ID VARCHAR(20),
    TAX_BOOK_TYPE NUMERIC(20),
    TAX_STRUCTURE_ID VARCHAR(20),
    PRINT_TAX_CODE_TEXT VARCHAR(5),
    NO_INVOICE_COPIES NUMERIC(20),
    DEF_MAN_SUPP_INV_TYPE VARCHAR(20),
    DEF_AUTO_INVOICE_TYPE VARCHAR(20),
    DEF_REC_MAN_SUPP_INV_TYPE VARCHAR(20),
    TAX_LIABILITY VARCHAR(20),
    WITHHOLDING_BASE_AMOUNT VARCHAR(4000),
    WITHHOLDING_BASE_AMOUNT_DB VARCHAR(20),
    INVOICE_RECIPIENT VARCHAR(20),
    INVOICING_SUPPLIER VARCHAR(20),
    MATCHING_LEVEL VARCHAR(4000),
    MATCHING_LEVEL_DB VARCHAR(20),
    ALLOW_TOLERANCE VARCHAR(5),
    CREATE_TOLERANCE_POSTING VARCHAR(5),
    ALLOW_QUANTITY_DIFF VARCHAR(5),
    DEFAULT_CURRENCY_RATE_TYPE VARCHAR(10),
    TAX_CERTIFICATE_FORM VARCHAR(4000),
    TAX_CERTIFICATE_FORM_DB VARCHAR(20),
    IS_NOTE VARCHAR(20),
    DELIV_TYPE_ID VARCHAR(20),
    SUP_VAT_FREE_VAT_CODE VARCHAR(20),
    SUP_COUNTRY_CODE VARCHAR(20),
    AUTOMATIC_PAY_AUTH_FLAG VARCHAR(4000),
    AUTOMATIC_PAY_AUTH_FLAG_DB VARCHAR(1),
    CUSTOMER_ID VARCHAR(20),
    SUPPLIER_ID VARCHAR(20),
    INACTIVE_REASON_DESC VARCHAR(1000),
    LEGAL_IDENTITY VARCHAR(4000),
    LEGAL_IDENTITY_DB VARCHAR(5),
    PO_REF_REC_REF_VAL_METHOD VARCHAR(4000),
    PO_REF_REC_REF_VAL_METHOD_DB VARCHAR(20),
    POSTING_TEMPLATE_ID VARCHAR(10),
    LEGAL_ID_NAME VARCHAR(100),
    LEGAL_ID_ADDR_ID VARCHAR(50),
    BI_TIMESTAMP DATE,
    INVOICE_REASON_ID VARCHAR(20),
    FISCAL_NO VARCHAR(16),
    INVOICE_RECIPIENT_FROM VARCHAR(4000),
    INVOICE_RECIPIENT_FROM_DB VARCHAR(20),
    EXC_FROM_SPESOMETRO_DEC VARCHAR(4000),
    EXC_FROM_SPESOMETRO_DEC_DB VARCHAR(20),
    SERVICE_CODE_REQUIRED VARCHAR(4000),
    SERVICE_CODE_REQUIRED_DB VARCHAR(20),
    EINVOICE_RECEIVER_CODE VARCHAR(7),
    PERSON_ID VARCHAR(20),
    CERTIFIED_EMAIL VARCHAR(200),
    TAX_REPRESENTATIVE VARCHAR(20),
    INC_INV_CURR_RATE_BASE VARCHAR(4000),
    INC_INV_CURR_RATE_BASE_DB VARCHAR(20),
    TAX_BUY_CURR_RATE_BASE VARCHAR(4000),
    TAX_BUY_CURR_RATE_BASE_DB VARCHAR(20),
    CIS_REFERENCE_ID NUMERIC(20),
    SUPPLIER_UTR VARCHAR(10),
    SUPPLY_TYPE_CODE VARCHAR(10),
    EINVOICE_PROCESS_TYPE VARCHAR(20),
    EXCLUDE_POSTING_AUTH VARCHAR(4000),
    EXCLUDE_POSTING_AUTH_DB VARCHAR(20),
    EXCLUDE_INVOICE_IMAGE VARCHAR(4000),
    EXCLUDE_INVOICE_IMAGE_DB VARCHAR(20),
    CONSOLIDATION_DAY VARCHAR(100),
    UTILITY_BILL_PROVIDER VARCHAR(4000),
    UTILITY_BILL_PROVIDER_DB VARCHAR(20),
    DIGITAL_INVOICE VARCHAR(4000),
    DIGITAL_INVOICE_DB VARCHAR(20),
    COUNTRY_TAX_REGISTERED VARCHAR(4000),
    COUNTRY_TAX_REGISTERED_DB VARCHAR(20),
    COUNTRY_CODE VARCHAR(20),
    CURRENCY_CODE VARCHAR(20),
    -- Colonnes de métadonnées pour l'ETL
    CREATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    UPDATED_BY VARCHAR(100),
    IS_DELETED BOOLEAN DEFAULT FALSE,
    -- Clé primaire composite
    PRIMARY KEY (COMPANY, IDENTITY, PARTY_TYPE)
);

-- Commentaires sur la table
COMMENT ON TABLE clean_data.identity_invoice_info IS 'Table des informations de facturation des identités (fournisseurs)';

-- Commentaires sur les colonnes principales
COMMENT ON COLUMN clean_data.identity_invoice_info.COMPANY IS 'Code société';
COMMENT ON COLUMN clean_data.identity_invoice_info.IDENTITY IS 'Identifiant du fournisseur';
COMMENT ON COLUMN clean_data.identity_invoice_info.PARTY_TYPE IS 'Type de partie (Supplier, Customer, etc.)';
COMMENT ON COLUMN clean_data.identity_invoice_info.PARTY_TYPE_DB IS 'Type de partie en base (SUPPLIER, CUSTOMER, etc.)';
COMMENT ON COLUMN clean_data.identity_invoice_info.DEF_CURRENCY IS 'Devise par défaut';
COMMENT ON COLUMN clean_data.identity_invoice_info.PAYM_DEV_DAYS IS 'Délai de paiement en jours';
COMMENT ON COLUMN clean_data.identity_invoice_info.IDENTITY_TYPE_DB IS 'Type d''identité en base (EXTERN, INTERN, etc.)';
COMMENT ON COLUMN clean_data.identity_invoice_info.AUTOMATIC_INVOICE IS 'Facturation automatique (Y/N)';
COMMENT ON COLUMN clean_data.identity_invoice_info.TAX_EXEMPT IS 'Exonération fiscale (Y/N)';
COMMENT ON COLUMN clean_data.identity_invoice_info.COUNTRY_TAX_REGISTERED IS 'Enregistré fiscalement dans le pays (Y/N)';

-- Index pour améliorer les performances
CREATE INDEX IF NOT EXISTS idx_identity_invoice_info_company ON clean_data.identity_invoice_info(COMPANY);
CREATE INDEX IF NOT EXISTS idx_identity_invoice_info_identity ON clean_data.identity_invoice_info(IDENTITY);
CREATE INDEX IF NOT EXISTS idx_identity_invoice_info_party_type ON clean_data.identity_invoice_info(PARTY_TYPE);
CREATE INDEX IF NOT EXISTS idx_identity_invoice_info_created_by ON clean_data.identity_invoice_info(CREATED_BY);
CREATE INDEX IF NOT EXISTS idx_identity_invoice_info_created_timestamp ON clean_data.identity_invoice_info(CREATED_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_identity_invoice_info_is_deleted ON clean_data.identity_invoice_info(IS_DELETED);
