-- ============================================================================
-- Table mara
-- Schema: raw_data
-- Role dans le module INVENTORY: SOURCE (lecture seule)
-- ============================================================================

CREATE TABLE IF NOT EXISTS raw_data.mara (
    mandt VARCHAR(20) NOT NULL,
    matnr VARCHAR(20) NOT NULL,
    ersda VARCHAR(20),
    ernam VARCHAR(20),
    laeda VARCHAR(20),
    aenam VARCHAR(20),
    vpsta VARCHAR(20),
    pstat VARCHAR(20),
    lvorm VARCHAR(20),
    mtart VARCHAR(20),
    mbrsh VARCHAR(20),
    matkl VARCHAR(20),
    bismt VARCHAR(20),
    meins VARCHAR(20),
    bstme VARCHAR(20),
    zeinr VARCHAR(22),
    zeiar VARCHAR(20),
    zeivr VARCHAR(20),
    zeifo VARCHAR(20),
    aeszn VARCHAR(20),
    blatt VARCHAR(20),
    blanz VARCHAR(20),
    ferth VARCHAR(20),
    formt VARCHAR(20),
    groes VARCHAR(32),
    wrkst VARCHAR(48),
    normt VARCHAR(20),
    labor VARCHAR(20),
    ekwsl VARCHAR(20),
    brgew VARCHAR(20),
    ntgew VARCHAR(20),
    gewei VARCHAR(20),
    volum VARCHAR(20),
    voleh VARCHAR(20),
    behvo VARCHAR(20),
    raube VARCHAR(20),
    tempb VARCHAR(20),
    disst VARCHAR(20),
    tragr VARCHAR(20),
    stoff VARCHAR(20),
    spart VARCHAR(20),
    kunnr VARCHAR(20),
    eannr VARCHAR(20),
    wesch VARCHAR(20),
    bwvor VARCHAR(20),
    bwscl VARCHAR(20),
    saiso VARCHAR(20),
    etiar VARCHAR(20),
    etifo VARCHAR(20),
    entar VARCHAR(20),
    ean11 VARCHAR(20),
    numtp VARCHAR(20),
    laeng VARCHAR(20),
    breit VARCHAR(20),
    hoehe VARCHAR(20),
    meabm VARCHAR(20),
    prdha VARCHAR(20),
    aeklk VARCHAR(20),
    cadkz VARCHAR(20),
    qmpur VARCHAR(20),
    ergew VARCHAR(20),
    ergei VARCHAR(20),
    ervol VARCHAR(20),
    ervoe VARCHAR(20),
    gewto VARCHAR(20),
    volto VARCHAR(20),
    vabme VARCHAR(20),
    kzrev VARCHAR(20),
    kzkfg VARCHAR(20),
    xchpf VARCHAR(20),
    vhart VARCHAR(20),
    fuelg VARCHAR(20),
    stfak VARCHAR(20),
    magrv VARCHAR(20),
    begru VARCHAR(20),
    datab VARCHAR(20),
    liqdt VARCHAR(20),
    saisj VARCHAR(20),
    plgtp VARCHAR(20),
    mlgut VARCHAR(20),
    extwg VARCHAR(20),
    satnr VARCHAR(20),
    attyp VARCHAR(20),
    kzkup VARCHAR(20),
    kznfm VARCHAR(20),
    pmata VARCHAR(20),
    mstae VARCHAR(20),
    mstav VARCHAR(20),
    mstde VARCHAR(20),
    mstdv VARCHAR(20),
    taklv VARCHAR(20),
    rbnrm VARCHAR(20),
    mhdrz VARCHAR(20),
    mhdhb VARCHAR(20),
    mhdlp VARCHAR(20),
    inhme VARCHAR(20),
    inhal VARCHAR(20),
    vpreh VARCHAR(20),
    etiag VARCHAR(20),
    inhbr VARCHAR(20),
    cmeth VARCHAR(20),
    cuobf VARCHAR(20),
    kzumw VARCHAR(20),
    kosch VARCHAR(20),
    sprof VARCHAR(20),
    nrfhg VARCHAR(20),
    mfrpn VARCHAR(40),
    mfrnr VARCHAR(20),
    bmatn VARCHAR(20),
    mprof VARCHAR(20),
    kzwsm VARCHAR(20),
    saity VARCHAR(20),
    profl VARCHAR(20),
    ihivi VARCHAR(20),
    iloos VARCHAR(20),
    serlv VARCHAR(20),
    kzgvh VARCHAR(20),
    xgchp VARCHAR(20),
    kzeff VARCHAR(20),
    compl VARCHAR(20),
    iprkz VARCHAR(20),
    rdmhd VARCHAR(20),
    przus VARCHAR(20),
    mtpos_mara VARCHAR(20),
    bflme VARCHAR(20),
    matfi VARCHAR(20),
    cmrel VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Contraintes
ALTER TABLE raw_data.mara ADD CONSTRAINT mara_pkey PRIMARY KEY (mandt, matnr);

-- Index
CREATE UNIQUE INDEX mara_pkey ON raw_data.mara USING btree (mandt, matnr);
