-- ============================================================================
-- Table mbew
-- Schema: raw_data
-- Role dans le module INVENTORY: SOURCE (lecture seule)
-- ============================================================================

CREATE TABLE IF NOT EXISTS raw_data.mbew (
    mandt VARCHAR(20) NOT NULL,
    matnr VARCHAR(20) NOT NULL,
    bwkey VARCHAR(20) NOT NULL,
    bwtar VARCHAR(20),
    lvorm VARCHAR(20),
    lbkum VARCHAR(20),
    salk3 VARCHAR(20),
    vprsv VARCHAR(20),
    verpr VARCHAR(20),
    stprs VARCHAR(20),
    peinh VARCHAR(20),
    bklas VARCHAR(20),
    salkv VARCHAR(20),
    vmkum VARCHAR(20),
    vmsal VARCHAR(20),
    vmvpr VARCHAR(20),
    vmver VARCHAR(20),
    vmstp VARCHAR(20),
    vmpei VARCHAR(20),
    vmbkl VARCHAR(20),
    vmsav VARCHAR(20),
    vjkum VARCHAR(20),
    vjsal VARCHAR(20),
    vjvpr VARCHAR(20),
    vjver VARCHAR(20),
    vjstp VARCHAR(20),
    vjpei VARCHAR(20),
    vjbkl VARCHAR(20),
    vjsav VARCHAR(20),
    lfgja VARCHAR(20),
    lfmon VARCHAR(20),
    bwtty VARCHAR(20),
    stprv VARCHAR(20),
    laepr VARCHAR(20),
    zkprs VARCHAR(20),
    zkdat VARCHAR(20),
    bwprs VARCHAR(20),
    bwprh VARCHAR(20),
    vjbws VARCHAR(20),
    vjbwh VARCHAR(20),
    vvjsl VARCHAR(20),
    vvjlb VARCHAR(20),
    vvmlb VARCHAR(20),
    vvsal VARCHAR(20),
    zplpr VARCHAR(20),
    zplp1 VARCHAR(20),
    zplp2 VARCHAR(20),
    zplp3 VARCHAR(20),
    zpld1 VARCHAR(20),
    zpld2 VARCHAR(20),
    zpld3 VARCHAR(20),
    pperz VARCHAR(20),
    pperl VARCHAR(20),
    pperv VARCHAR(20),
    kalkz VARCHAR(20),
    kalkl VARCHAR(20),
    kalkv VARCHAR(20),
    kalsc VARCHAR(20),
    xlifo VARCHAR(20),
    mypol VARCHAR(20),
    bwph1 VARCHAR(20),
    bwps1 VARCHAR(20),
    abwkz VARCHAR(20),
    pstat VARCHAR(20),
    kaln1 VARCHAR(20),
    kalnr VARCHAR(20),
    bwva1 VARCHAR(20),
    bwva2 VARCHAR(20),
    bwva3 VARCHAR(20),
    vers1 VARCHAR(20),
    vers2 VARCHAR(20),
    vers3 VARCHAR(20),
    hrkft VARCHAR(20),
    kosgr VARCHAR(20),
    pprdz VARCHAR(20),
    pprdl VARCHAR(20),
    pprdv VARCHAR(20),
    pdatz VARCHAR(20),
    pdatl VARCHAR(20),
    pdatv VARCHAR(20),
    ekalr VARCHAR(20),
    vplpr VARCHAR(20),
    mlmaa VARCHAR(20),
    mlast VARCHAR(20),
    lplpr VARCHAR(20),
    vksal VARCHAR(20),
    hkmat VARCHAR(20),
    sperw VARCHAR(20),
    kziwl VARCHAR(20),
    wlinl VARCHAR(20),
    abciw VARCHAR(20),
    bwspa VARCHAR(20),
    lplpx VARCHAR(20),
    vplpx VARCHAR(20),
    fplpx VARCHAR(20),
    lbwst VARCHAR(20),
    vbwst VARCHAR(20),
    fbwst VARCHAR(20),
    eklas VARCHAR(20),
    qklas VARCHAR(20),
    mtuse VARCHAR(20),
    mtorg VARCHAR(20),
    ownpr VARCHAR(20),
    xbewm VARCHAR(20),
    bwpei VARCHAR(20),
    mbrue VARCHAR(20),
    oklas VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Contraintes
ALTER TABLE raw_data.mbew ADD CONSTRAINT mbew_pkey PRIMARY KEY (mandt, matnr, bwkey);

-- Index
CREATE UNIQUE INDEX mbew_pkey ON raw_data.mbew USING btree (mandt, matnr, bwkey);
