-- ============================================================================
-- Table lfa1
-- Schema: raw_data
-- Role dans le module INVENTORY: SOURCE (lecture seule)
-- ============================================================================

CREATE TABLE IF NOT EXISTS raw_data.lfa1 (
    mandt VARCHAR(20) NOT NULL,
    lifnr VARCHAR(20) NOT NULL,
    land1 VARCHAR(20),
    name1 VARCHAR(35),
    name2 VARCHAR(35),
    name3 VARCHAR(35),
    name4 VARCHAR(35),
    ort01 VARCHAR(35),
    ort02 VARCHAR(35),
    pfach VARCHAR(20),
    pstl2 VARCHAR(20),
    pstlz VARCHAR(20),
    regio VARCHAR(20),
    sortl VARCHAR(20),
    stras VARCHAR(35),
    adrnr VARCHAR(20),
    mcod1 VARCHAR(25),
    mcod2 VARCHAR(25),
    mcod3 VARCHAR(25),
    anred VARCHAR(20),
    bahns VARCHAR(25),
    bbbnr VARCHAR(20),
    bbsnr VARCHAR(20),
    begru VARCHAR(20),
    brsch VARCHAR(20),
    bubkz VARCHAR(20),
    datlt VARCHAR(20),
    dtams VARCHAR(20),
    dtaws VARCHAR(20),
    erdat VARCHAR(20),
    ernam VARCHAR(20),
    esrnr VARCHAR(20),
    konzs VARCHAR(20),
    ktokk VARCHAR(20),
    kunnr VARCHAR(20),
    lnrza VARCHAR(20),
    loevm VARCHAR(20),
    sperr VARCHAR(20),
    sperm VARCHAR(20),
    spras VARCHAR(20),
    stcd1 VARCHAR(20),
    stcd2 VARCHAR(20),
    stkza VARCHAR(20),
    stkzu VARCHAR(20),
    telbx VARCHAR(20),
    telf1 VARCHAR(20),
    telf2 VARCHAR(20),
    telfx VARCHAR(31),
    teltx VARCHAR(30),
    telx1 VARCHAR(30),
    xcpdk VARCHAR(20),
    xzemp VARCHAR(20),
    vbund VARCHAR(20),
    fiskn VARCHAR(20),
    stceg VARCHAR(20),
    stkzn VARCHAR(20),
    sperq VARCHAR(20),
    gbort VARCHAR(25),
    gbdat VARCHAR(20),
    sexkz VARCHAR(20),
    kraus VARCHAR(20),
    revdb VARCHAR(20),
    qssys VARCHAR(20),
    ktock VARCHAR(20),
    pfort VARCHAR(35),
    werks VARCHAR(20),
    ltsna VARCHAR(20),
    werkr VARCHAR(20),
    plkal VARCHAR(20),
    duefl VARCHAR(20),
    txjcd VARCHAR(20),
    sperz VARCHAR(20),
    scacd VARCHAR(20),
    sfrgr VARCHAR(20),
    lzone VARCHAR(20),
    xlfza VARCHAR(20),
    dlgrp VARCHAR(20),
    fityp VARCHAR(20),
    stcdt VARCHAR(20),
    regss VARCHAR(20),
    actss VARCHAR(20),
    stcd3 VARCHAR(20),
    stcd4 VARCHAR(20),
    ipisp VARCHAR(20),
    taxbs VARCHAR(20),
    profs VARCHAR(30),
    stgdl VARCHAR(20),
    emnfr VARCHAR(20),
    lfurl VARCHAR(132),
    j_1kfrepre VARCHAR(20),
    j_1kftbus VARCHAR(30),
    j_1kftind VARCHAR(30),
    confs VARCHAR(20),
    updat VARCHAR(20),
    uptim VARCHAR(20),
    nodel VARCHAR(20),
    qssysdat VARCHAR(20),
    podkzb VARCHAR(20),
    fisku VARCHAR(20),
    stenr VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Contraintes
ALTER TABLE raw_data.lfa1 ADD CONSTRAINT lfa1_pkey PRIMARY KEY (mandt, lifnr);

-- Index
CREATE UNIQUE INDEX lfa1_pkey ON raw_data.lfa1 USING btree (mandt, lifnr);
