export const SUPPLIER_TABLE_CONFIG = {
  'SUPPLIER_INFO_GENERAL': [
    'SUPPLIER_ID', 'NAME', 'CREATION_DATE', 'ASSOCIATION_NO', 'PARTY', 'DEFAULT_DOMAIN',
    'DEFAULT_LANGUAGE', 'DEFAULT_LANGUAGE_DB', 'COUNTRY', 'COUNTRY_DB', 'PARTY_TYPE',
    'PARTY_TYPE_DB', 'SUPPLIERS_OWN_ID', 'CORPORATE_FORM', 'IDENTIFIER_REFERENCE',
    'IDENTIFIER_REF_VALIDATION', 'IDENTIFIER_REF_VALIDATION_DB', 'PICTURE_ID', 'ONE_TIME',
    'ONE_TIME_DB', 'SUPPLIER_CATEGORY', 'SUPPLIER_CATEGORY_DB', 'B2B_SUPPLIER',
    'B2B_SUPPLIER_DB', 'BUSINESS_CLASSIFICATION'
  ],
  'SUPPLIER_INFO_ADDRESS': [
    'SUPPLIER_ID', 'ADDRESS_ID', 'NAME', 'ADDRESS', 'EAN_LOCATION', 'VALID_FROM',
    'VALID_TO', 'PARTY', 'DEFAULT_DOMAIN', 'COUNTRY', 'COUNTRY_DB', 'PARTY_TYPE',
    'PARTY_TYPE_DB', 'ADDRESS1', 'ADDRESS2', 'ADDRESS3', 'ADDRESS4', 'ADDRESS5',
    'ADDRESS6', 'ZIP_CODE', 'CITY', 'COUNTY', 'STATE', 'COMM_ID', 'OUTPUT_MEDIA',
    'OUTPUT_MEDIA_DB', 'SUPPLIER_BRANCH'
  ],
  'SUPPLIER_INFO_ADDRESS_TYPE': [
    'SUPPLIER_ID', 'ADDRESS_ID', 'ADDRESS_TYPE_CODE', 'ADDRESS_TYPE_CODE_DB',
    'PARTY', 'DEF_ADDRESS', 'DEFAULT_DOMAIN'
  ],
  'SUPPLIER_INFO_OUR_ID': [
    'SUPPLIER_ID', 'COMPANY'
  ],
  'COMM_METHOD': [
    'PARTY_TYPE', 'PARTY_TYPE_DB', 'IDENTITY', 'COMM_ID', 'VALUE', 'DESCRIPTION',
    'VALID_FROM', 'VALID_TO', 'METHOD_DEFAULT', 'ADDRESS_DEFAULT', 'NAME',
    'METHOD_ID', 'METHOD_ID_DB', 'ADDRESS_ID', 'CUSTOMER_ID', 'SUPPLIER_ID',
    'COMPANY_ID', 'PERSON_ID', 'CUSTOMS_ID', 'FORWARDER_ID', 'MANUFACTURER_ID',
    'OWNER_ID', 'TAX_OFFICE_ID'
  ],
  'SUPPLIER_ADDRESS': [
    'VENDOR_NO', 'ADDR_NO', 'DELIVERY_TERMS', 'SHIP_VIA_CODE', 'ROUTE_ID',
    'CONTACT', 'INTRASTAT_EXEMPT', 'INTRASTAT_EXEMPT_DB', 'DEL_TERMS_LOCATION',
    'SUPPLIER_CALENDAR_ID'
  ],
  'SUPPLIER_DOCUMENT_TAX_INFO': [
    'SUPPLIER_ID', 'ADDRESS_ID', 'COMPANY', 'TAX_ID_TYPE', 'VAT_NO',
    'VALIDATED_DATE', 'RELIABILITY_STATUS', 'RELIABILITY_STATUS_DB',
    'DECLARATION_DATE', 'LAST_MODIFY_DATE', 'TAX_OFFICE_ID'
  ],
  'SUPPLIER_DELIVERY_TAX_CODE': [
    'SUPPLIER_ID', 'ADDRESS_ID', 'COMPANY', 'TAX_CODE'
  ],
  'SUPPLIER': [
    'VENDOR_NO', 'NAME', 'BUYER_CODE', 'CURRENCY_CODE', 'SUPP_GRP', 'ADDITIONAL_COST_AMOUNT',
    'CONTACT', 'CR_CHECK', 'CR_CHECK_DB', 'CR_DATE', 'CR_NOTE_TEXT', 'DATE_DEL',
    'DISCOUNT', 'NOTE_TEXT', 'OUR_CUSTOMER_NO', 'PACK_LIST_FLAG', 'PACK_LIST_FLAG_DB',
    'PURCH_ORDER_FLAG', 'PURCH_ORDER_FLAG_DB', 'QC_APPROVAL', 'QC_APPROVAL_DB',
    'QC_DATE', 'QC_AUDIT', 'QC_NOTE_TEXT', 'ORD_CONF_REM_INTERVAL', 'DELIVERY_REM_INTERVAL',
    'DAYS_BEFORE_DELIVERY', 'DAYS_BEFORE_ARRIVAL', 'ORD_CONF_REMINDER', 'ORD_CONF_REMINDER_DB',
    'DELIVERY_REMINDER', 'DELIVERY_REMINDER_DB', 'CATEGORY', 'CATEGORY_DB', 'ACQUISITION_SITE',
    'COMPANY', 'PAY_TERM_ID', 'EDI_AUTO_APPROVAL_USER', 'QC_TYPE', 'ENVIRONMENT_DATE',
    'ENVIRONMENT_TYPE', 'ENVIRONMENTAL_APPROVAL', 'ENVIRONMENTAL_APPROVAL_DB', 'ENVIRONMENT_AUDIT',
    'ENVIRONMENT_NOTE_TEXT', 'COC_APPROVAL', 'COC_APPROVAL_DB', 'COC_DATE', 'COC_TYPE',
    'COC_AUDIT', 'COC_NOTE_TEXT', 'CUSTOMER_NO', 'NOTE_ID', 'SUPPLIER_TEMPLATE_DESC',
    'TEMPLATE_SUPPLIER', 'TEMPLATE_SUPPLIER_DB', 'QUICK_REGISTERED_SUPPLIER',
    'QUICK_REGISTERED_SUPPLIER_DB', 'BLANKET_DATE', 'BLANKET_DATE_DB', 'EXPRESS_ORDER_ALLOWED',
    'EXPRESS_ORDER_ALLOWED_DB', 'EDI_PRI_CAT_APP_USER', 'PRICAT_AUTOMATIC_APPROVAL',
    'PRICAT_AUTOMATIC_APPROVAL_DB', 'AUTOMATIC_REPL_CHANGE', 'AUTOMATIC_REPL_CHANGE_DB',
    'SEND_CHANGE_MESSAGE', 'SEND_CHANGE_MESSAGE_DB', 'RECEIPT_REF_REMINDER',
    'RECEIPT_REF_REMINDER_DB', 'PRINT_AMOUNTS_INCL_TAX', 'PRINT_AMOUNTS_INCL_TAX_DB',
    'CLOSING_DAY', 'END_OF_MONTH', 'END_OF_MONTH_DB', 'RECEIVING_ADVICE_TYPE',
    'RECEIVING_ADVICE_TYPE_DB', 'REC_ADV_SELF_BILLING', 'REC_ADV_SELF_BILLING_DB',
    'CLASSIFICATION_STANDARD', 'PURCHASE_CODE', 'PO_CHANGE_MANAGEMENT', 'PO_CHANGE_MANAGEMENT_DB',
    'CREATE_CONFIRMATION_CHG_ORD', 'CREATE_CONFIRMATION_CHG_ORD_DB', 'EMAIL_PURCHASE_ORDER',
    'EMAIL_PURCHASE_ORDER_DB', 'VENDOR_CATEGORY_DB', 'DIR_DEL_APPROVAL', 'DIR_DEL_APPROVAL_DB',
    'ORDER_CONF_APPROVAL', 'ORDER_CONF_APPROVAL_DB', 'ORDER_CONF_DIFF_APPROVAL',
    'ORDER_CONF_DIFF_APPROVAL_DB', 'ADHOC_PUR_RQST_APPROVAL', 'ADHOC_PUR_RQST_APPROVAL_DB',
    'TAX_LIABILITY', 'B2B_CONF_ORDER_WITH_DIFF', 'B2B_CONF_ORDER_WITH_DIFF_DB',
    'QUALITY_SYSTEM_LEVEL_ID', 'QUALITY_AUDIT_ID', 'ENVIRONMENT_AUDIT_ID', 'COC_AUDIT_ID',
    'REC_ADV_SB_CONSIGNMENT', 'REC_ADV_SB_CONSIGNMENT_DB', 'REC_ADV_SB_MIX_OWNERSHIP',
    'REC_ADV_SB_MIX_OWNERSHIP_DB'
  ],
  'IDENTITY_INVOICE_INFO': [
    'COMPANY', 'IDENTITY', 'PARTY_TYPE', 'PARTY_TYPE_DB', 'INVOICE_FEE', 'EXPIRE_DATE',
    'NATIONAL_BANK_CODE', 'GROUP_ID', 'DEF_AUTHORIZER', 'PAY_TERM_ID', 'DEF_VAT_CODE',
    'ROUNDING_TAX_CODE', 'DEF_CURRENCY', 'PAYM_DEV_DAYS', 'IDENTITY_TYPE', 'IDENTITY_TYPE_DB',
    'VOTING_SHARE_PERCENTAGE', 'VOTING_SHARE_PERCENTAGE_DB', 'DEF_PRELIMINARY_CODE',
    'AUTOMATIC_INVOICE', 'PERCENT_TOLERANCE', 'AMOUNT_TOLERANCE', 'NCF_REFERENCE_CHECK',
    'TAX_EXEMPT', 'TAX_EXEMPT_VALID_FROM', 'TAX_EXEMPT_VALID_TO', 'SECOND_TIN',
    'REPORT_AND_WITHHOLD', 'REPORT_AND_WITHHOLD_DB', 'SUPPLIER_TAX_OFFICE_ID',
    'NUMERATION_GROUP', 'TAX_BOOK_ID', 'TAX_BOOK_TYPE', 'TAX_STRUCTURE_ID',
    'PRINT_TAX_CODE_TEXT', 'NO_INVOICE_COPIES'
  ],
  'IDENTITY_PAY_INFO': [
    'COMPANY', 'IDENTITY', 'PARTY_TYPE', 'PARTY_TYPE_DB', 'PRIORITY', 'BLOCKED_FOR_PAYMENT',
    'OTHER_PAYEE_IDENTITY', 'INTEREST_TEMPLATE', 'REMINDER_TEMPLATE', 'PAYMENT_DELAY',
    'AMOUNT_TOLERANCE', 'PERCENT_TOLERANCE', 'DISC_DAYS_TOLERANCE', 'NETTING_ALLOWED',
    'FORMAT_NO', 'PAYMENT_ADVICE', 'PAYMENT_ADVICE_DB', 'DEDUCTION_GROUP', 'CORPORATION_ID',
    'MEMBER_ID', 'SEND_REMINDER_TO_PAYER', 'SEND_INTEREST_INV_TO_PAYER', 'RULE_ID',
    'PAYMENT_RECEIPT_TYPE', 'PAYMENT_RECEIPT_TYPE_DB', 'TEMPLATE_ID', 'CHECK_RECIPIENT',
    'CHECK_RECIPIENT_DB', 'SEND_STMT_OF_ACC_TO_PAYER', 'AR_CONTACT', 'COMM_ID',
    'OUTPUT_MEDIA', 'OUTPUT_MEDIA_DB', 'DEFAULT_PAYMENT_METHOD', 'CUSTOMER_ID',
    'SUPPLIER_ID', 'NEXT_PAYMENT_MATCHING_ID', 'IS_ONE_INV_PER_PAY', 'IS_ONE_INV_PER_PAY_DB',
    'PAYMENT_MODE', 'PAYMENT_MODE_DB', 'PREDICTED_PAYMENT_DELAY', 'PREDICTED_PAYMENT_DELAY_DB'
  ],
  'PAYMENT_WAY_PER_IDENTITY': [
    'IDENTITY', 'PARTY_TYPE', 'PARTY_TYPE_DB', 'WAY_ID', 'DEFAULT_PAYMENT_WAY'
  ],
  'PAYMENT_ADDRESS': [
    'COMPANY', 'IDENTITY', 'PARTY_TYPE', 'PARTY_TYPE_DB', 'WAY_ID', 'ADDRESS_ID',
    'DESCRIPTION', 'DEFAULT_ADDRESS', 'ACCOUNT', 'DATA1', 'DATA2', 'DATA3', 'DATA4',
    'DATA5', 'DATA6', 'DATA7', 'DATA8', 'DATA9', 'DATA10', 'DATA11', 'DATA12',
    'DATA13', 'DATA14', 'DATA15', 'DATA16', 'DATA17', 'DATA18', 'DATA18_DB',
    'DATA19', 'DATA19_DB', 'DATA20', 'DATA20_DB', 'DATA21', 'DATA22', 'DATA23',
    'DATA24', 'DATA25', 'DATA26', 'DATA27', 'DATA28', 'DATA29', 'DATA30',
    'DATA31', 'DATA32', 'DATA33', 'DATA34', 'DATA35', 'DATA36', 'DATA37',
    'DATA38', 'DATA39', 'DATA40', 'DATA41', 'BIC_CODE', 'BLOCKED_FOR_USE',
    'MAPPING_TYPE', 'BANK_ACCOUNT_VALIDATED', 'BANK_ACCOUNT_VALIDATED_DB',
    'BANK_ACCOUNT_VALID_DATE'
  ],
  'SUPPLIER_TAX_INFO': [
    'SUPPLIER_ID', 'ADDRESS_ID', 'COMPANY', 'USE_SUPP_ADDRESS_FOR_TAX',
    'USE_SUPP_ADDRESS_FOR_TAX_DB', 'TAX_CALC_STRUCTURE_ID', 'ICMS_TAX_PAYER',
    'ICMS_TAX_PAYER_DB', 'BUSINESS_TRANSACTION_ID'
  ],
  'SUPPLIER_INFO_CONTACT': [
    'SUPPLIER_ID', 'PERSON_ID', 'GUID', 'ROLE', 'ROLE_DB', 'SUPPLIER_PRIMARY',
    'SUPPLIER_SECONDARY', 'ADDRESS_PRIMARY', 'ADDRESS_SECONDARY', 'CREATED',
    'CHANGED', 'NOTE_TEXT', 'SUPPLIER_ADDRESS', 'CONNECT_ALL_SUPP_ADDR',
    'CONNECT_ALL_SUPP_ADDR_DB', 'CONTACT_ADDRESS', 'CREATED_BY', 'CHANGED_BY',
    'DEPARTMENT', 'DEPARTMENT_DB', 'MAIN_REPRESENTATIVE_ID'
  ]
} as const;

export type SupplierTableName = keyof typeof SUPPLIER_TABLE_CONFIG;

// Liste des tables par défaut sélectionnées
export const DEFAULT_SELECTED_TABLES: SupplierTableName[] = [
  'SUPPLIER_INFO_GENERAL',
  'SUPPLIER_INFO_ADDRESS',
  'SUPPLIER_INFO_ADDRESS_TYPE',
  'SUPPLIER_INFO_OUR_ID',
  'COMM_METHOD',
  'SUPPLIER_ADDRESS',
  'SUPPLIER_DOCUMENT_TAX_INFO',
  'SUPPLIER_DELIVERY_TAX_CODE',
  'SUPPLIER',
  'IDENTITY_INVOICE_INFO',
  'IDENTITY_PAY_INFO',
  'PAYMENT_WAY_PER_IDENTITY',
  'PAYMENT_ADDRESS',
  'SUPPLIER_TAX_INFO',
  'SUPPLIER_INFO_CONTACT'
]; 