CREATE TABLE IF NOT EXISTS raw_data.sharepoint_project_to_save (
    "Numéro du projet"                          TEXT,
    "URL du site"                               TEXT,
    "Nom du projet"                             TEXT,
    "Chef de projet"                            TEXT,
    "Correspondant/ Client du projet"           TEXT,
    "Acheteur CAPEX"                            TEXT,
    "% Complété"                                TEXT,
    "Passage porte"                             TEXT,
    "Statut Global"                             TEXT,
    "Santé"                                     TEXT,
    "Coût"                                      TEXT,
    "Planning"                                  TEXT,
    "Numéro de crédit"                          TEXT,
    "Budget Initial"                            TEXT,
    "Budget Total SAP"                          TEXT,
    "Engagé"                                    TEXT,
    "Réceptionné"                               TEXT,
    "Pris en charge"                            TEXT,
    "Reste à engager"                           TEXT,
    "Date de début"                             TEXT,
    "P0"                                        TEXT,
    "P1"                                        TEXT,
    "P2"                                        TEXT,
    "P3"                                        TEXT,
    "P4"                                        TEXT,
    "P6"                                        TEXT,
    "Date ouverture crédit"                     TEXT,
    "Date de fin estimée"                       TEXT,
    "Dernière MAJ de l'état d'avancement"       TEXT,
    "État CFV Conception"                       TEXT,
    "Date CFV Conception"                       TEXT,
    "État CFV Mise en service"                  TEXT,
    "Date CFV Mise en service"                  TEXT,
    "État CFV Achèvement industriel"            TEXT,
    "Date CFV Achèvement industriel"            TEXT,
    "Correspondant Maintenance"                 TEXT,
    "Phase"                                     TEXT,
    "Budget demandé"                            TEXT,
    "Budget 1ère P3"                            TEXT,
    "Equipe projet"                             TEXT,
    "Secteur"                                   TEXT,
    "Site"                                      TEXT,
    "Budget EX SAP"                             TEXT,
    "Budget IM SAP"                             TEXT,
    "Date du dernier jalon passé"               TEXT,
    "Priorité"                                  TEXT,
    "Sponsor"                                   TEXT,
    "Type d'élément"                            TEXT,
    "Chemin d'accès"                            TEXT,
    source_file                                 TEXT,
    loaded_at                                   TIMESTAMP DEFAULT now()
);

-- Verification post-execution : nombre de colonnes attendu = 52
-- (49 colonnes source + raw_id + source_file + loaded_at)
-- SELECT count(*) FROM information_schema.columns
-- WHERE table_schema='raw_data' AND table_name='share_project_to_save';