-- ============================================================================
-- Table ifs_article_maitre
-- Schéma: clean_data
-- Table principale pour stocker les articles IFS
-- ============================================================================

CREATE TABLE IF NOT EXISTS clean_data.ifs_article_maitre (
    numero_article VARCHAR(20),
    designation VARCHAR(255),
    designation_courte VARCHAR(40),
    ancien_numero VARCHAR(20),
    type_article VARCHAR(20),
    libelle_type_article TEXT,
    groupe_article VARCHAR(20),
    libelle_groupe_article VARCHAR(20),
    secteur_activite VARCHAR(20),
    unite_base VARCHAR(20),
    unite_commande VARCHAR(20),
    nombre_centres_actifs BIGINT,
    centres_list TEXT,
    groupes_achat_list TEXT,
    strategies_list TEXT,
    stock_minimum_total NUMERIC,
    stock_securite_total NUMERIC,
    stock_maximum_total NUMERIC,
    avec_gestion_lot TEXT,
    profils_serie_list TEXT,
    organisations_commerciales_list TEXT,
    canaux_distribution_list TEXT,
    statuts_commerciaux_list TEXT,
    cercles_evaluation_list TEXT,
    prix_moyen_pondere_moyen NUMERIC,
    prix_standard_moyen NUMERIC,
    stock_quantite_total NUMERIC,
    valeur_stock_total NUMERIC,
    classes_evaluation_list TEXT,
    nombre_magasins BIGINT,
    stock_total_libre NUMERIC,
    stock_total_bloque NUMERIC,
    stock_total_controle NUMERIC,
    valeur_stock_magasins_total NUMERIC,
    fournisseur_principal VARCHAR(20),
    unite_commande_achat VARCHAR(20),
    nom_fournisseur_principal VARCHAR(35),
    pays_fournisseur_principal VARCHAR(20),
    ville_fournisseur_principal VARCHAR(35),
    actif_dans_centre TEXT,
    actif_commercial TEXT,
    actif_evaluation TEXT,
    actif_achat TEXT,
    avec_stock TEXT,
    statut_utilisation TEXT,
    date_creation VARCHAR(20),
    createur VARCHAR(20),
    date_modification VARCHAR(20),
    modificateur VARCHAR(20),
    langue VARCHAR(20),
    codification_id VARCHAR(25)
);

COMMENT ON TABLE clean_data.ifs_article_maitre IS 'Table des articles maîtres pour migration vers IFS';
