-- ============================================================================
-- Table part_catalog
-- Schema: clean_data
-- Role dans le module INVENTORY: CIBLE (TRUNCATE + INSERT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS clean_data.part_catalog (
    part_no VARCHAR(25),
    description VARCHAR(200),
    std_name_id NUMERIC(10,0),
    unit_code VARCHAR(30),
    lot_tracking_code_db VARCHAR(30),
    serial_rule_db VARCHAR(20),
    serial_tracking_code_db VARCHAR(30),
    eng_serial_tracking_code_db VARCHAR(20),
    configurable_db VARCHAR(20),
    condition_code_usage_db VARCHAR(20),
    sub_lot_rule_db VARCHAR(20),
    lot_quantity_rule_db VARCHAR(20),
    position_part_db VARCHAR(20),
    catch_unit_enabled_db VARCHAR(5),
    multilevel_tracking_db VARCHAR(20),
    component_lot_rule_db VARCHAR(20),
    stop_arrival_issued_serial_db VARCHAR(5),
    allow_as_not_consumed_db VARCHAR(5),
    receipt_issue_serial_track_db VARCHAR(20),
    stop_new_serial_in_rma_db VARCHAR(20),
    language_description VARCHAR(4000),
    info_text VARCHAR(2000),
    lot_tracking_code VARCHAR(4000),
    serial_rule VARCHAR(4000),
    serial_tracking_code VARCHAR(4000),
    eng_serial_tracking_code VARCHAR(4000),
    configurable VARCHAR(4000),
    condition_code_usage VARCHAR(4000),
    sub_lot_rule VARCHAR(4000),
    lot_quantity_rule VARCHAR(4000),
    position_part VARCHAR(4000),
    catch_unit_enabled VARCHAR(4000),
    multilevel_tracking VARCHAR(4000),
    component_lot_rule VARCHAR(4000),
    stop_arrival_issued_serial VARCHAR(4000),
    allow_as_not_consumed VARCHAR(4000),
    receipt_issue_serial_track VARCHAR(4000),
    stop_new_serial_in_rma VARCHAR(4000),
    product_type_classif VARCHAR(4000),
    part_main_group VARCHAR(20),
    cust_warranty_id NUMERIC(20,0),
    sup_warranty_id NUMERIC(20,0),
    input_unit_meas_group_id VARCHAR(30),
    weight_net NUMERIC(20,0),
    uom_for_weight_net VARCHAR(30),
    volume_net NUMERIC(20,0),
    uom_for_volume_net VARCHAR(30),
    freight_factor NUMERIC(20,0),
    technical_drawing_no VARCHAR(25),
    product_type_classif_db VARCHAR(35),
    cest_code VARCHAR(7),
    fci_code VARCHAR(36)
);
