-- ============================================================================
-- Table purchase_part
-- Schema: clean_data
-- Role dans le module INVENTORY: CIBLE (TRUNCATE + INSERT)
-- ============================================================================

CREATE TABLE IF NOT EXISTS clean_data.purchase_part (
    contract VARCHAR(5),
    part_no VARCHAR(25),
    description VARCHAR(200),
    eng_attribute VARCHAR(5),
    note_id NUMERIC(20,0),
    qc_code VARCHAR(20),
    stat_grp VARCHAR(6),
    close_code VARCHAR(4000),
    close_code_db VARCHAR(1),
    close_tolerance NUMERIC(20,0),
    date_cre TIMESTAMP,
    inventory_flag VARCHAR(4000),
    inventory_flag_db VARCHAR(1),
    note_text VARCHAR(2000),
    qc_date TIMESTAMP,
    default_buy_unit_meas VARCHAR(10),
    over_delivery_tolerance NUMERIC(20,0),
    over_delivery VARCHAR(4000),
    over_delivery_db VARCHAR(20),
    buyer_code VARCHAR(20),
    process_type VARCHAR(3),
    standard_pack_size NUMERIC(20,0),
    technical_coordinator_id VARCHAR(4000),
    taxable VARCHAR(4000),
    taxable_db VARCHAR(5),
    dop_pegged_po_update_flag VARCHAR(4000),
    dop_pegged_po_update_flag_db VARCHAR(20),
    acquisition_type VARCHAR(4000),
    acquisition_type_db VARCHAR(20),
    action_non_authorized VARCHAR(4000),
    action_non_authorized_db VARCHAR(20),
    action_authorized VARCHAR(4000),
    action_authorized_db VARCHAR(20),
    external_resource VARCHAR(4000),
    external_resource_db VARCHAR(5),
    statistical_code VARCHAR(15),
    statistical_code_manuf VARCHAR(15),
    quality_system_level_id VARCHAR(50),
    qsl_approval_template VARCHAR(10),
    qualified_manufacturer VARCHAR(4000),
    qualified_manufacturer_db VARCHAR(20),
    qmr_approval_template VARCHAR(10),
    qualified_supplier VARCHAR(4000),
    qualified_supplier_db VARCHAR(20),
    qsr_approval_template VARCHAR(10),
    acquisition_origin NUMERIC(20,0),
    acquisition_reason_id VARCHAR(10),
    package_part_flag VARCHAR(4000),
    package_part_flag_db VARCHAR(5),
    std_name_description VARCHAR(200),
    company VARCHAR(20),
    nbs_code VARCHAR(50),
    objversion VARCHAR(50),
    objid VARCHAR(50),
    std_name_id VARCHAR(50)
);
