-- ============================================================================
-- Vue v_phl_article_retenu
-- Schema: raw_data
-- ============================================================================

CREATE OR REPLACE VIEW raw_data.v_phl_article_retenu AS 
 WITH base AS (
         SELECT phl."NUMERO",
            phl."N. ARTICLE",
            phl."ALLIAGE",
            phl."SERIE ALL",
            phl."STATUT",
            phl."DIAMETRE",
            phl."NUM PRODUIT",
            phl."FAMILLE",
            phl."FORME",
            phl."SCIAGE",
            phl."NORME CHARGE",
            phl."POIDS COMMERCIAL",
            phl."EPAISSEUR",
            phl."LONGUEUR",
            phl."LARGEUR",
            phl."DESCRIPTION",
            phl."DESCRIPTION LANGUE",
            phl."TEXTE INFO",
            phl."ID NOM STD",
            phl."U/M",
            phl."TRACABILITE LOTS",
            phl."TRACABILITE LOTS_2",
            phl."REGLE DE SERIE",
            phl."REGLE DE SERIE_2",
            phl."SUIVI DES SERIES",
            phl."SUIVI DES SERIES_2",
            phl."SUIVI SERIES APRES",
            phl."SUIVI SERIES APRES_2",
            phl."GP PRINCP ARTICLE",
            phl."CONFIGURABLE",
            phl."CONFIGURABLE_2",
            phl."ID GARANTIE CLIENT",
            phl."GARANTIE FOURNI.",
            phl."AUTORISE CD COND",
            phl."AUTORISE CD COND_2",
            phl."REGLE SOUS-LOT",
            phl."REGLE SOUS-LOT_2",
            phl."REGLE DU LOT",
            phl."REGLE DU LOT_2",
            phl."ARTICLE POSITION",
            phl."ARTICLE POSITION_2",
            phl."ENTREE ID GP U/M",
            phl."U/M CAP. ACTIVE E",
            phl."U/M CAP. ACTIVE E_2",
            phl."TRACAB. MULT NIV.",
            phl."TRACAB. MULT NIV._2",
            phl."REGLE LOT COMPOS.",
            phl."REGLE LOT COMPOS._2",
            phl."ARR.BC NUM SORTIS",
            phl."ARR.BC NUM SORTIS_2",
            phl."POIDS NET",
            phl."U/M POIDS",
            phl."VOLUME NET",
            phl."U/M VOLUME",
            phl."FACTEUR CHARGEMENT",
            phl."AUTOR. NON CONSOM.",
            phl."AUTOR. NON CONSOM._2",
            phl."RECEPT./SORTIE",
            phl."RECEPT./SORTIE_2",
            phl."AR.CREA.SERIE RMA",
            phl."AR.CREA.SERIE RMA_2",
            phl."N.DESSIN TECHN.",
            phl."CLASSIF TYPE PROD.",
            phl."CLASSIF TYPE PROD._2",
            phl."CODE CEST",
            phl."CODE FCI",
                CASE
                    WHEN TRIM(BOTH FROM phl."N. ARTICLE") ~ '-[A-Za-z]$'::text THEN "left"(TRIM(BOTH FROM phl."N. ARTICLE"), length(TRIM(BOTH FROM phl."N. ARTICLE")) - 2)
                    ELSE TRIM(BOTH FROM phl."N. ARTICLE")
                END AS radical_article
           FROM raw_data.phl_article phl
          WHERE NULLIF(TRIM(BOTH FROM phl."N. ARTICLE"), ''::text) IS NOT NULL
        )
 SELECT DISTINCT ON (base.radical_article) base."NUMERO",
    base."N. ARTICLE",
    base."ALLIAGE",
    base."SERIE ALL",
    base."STATUT",
    base."DIAMETRE",
    base."NUM PRODUIT",
    base."FAMILLE",
    base."FORME",
    base."SCIAGE",
    base."NORME CHARGE",
    base."POIDS COMMERCIAL",
    base."EPAISSEUR",
    base."LONGUEUR",
    base."LARGEUR",
    base."DESCRIPTION",
    base."DESCRIPTION LANGUE",
    base."TEXTE INFO",
    base."ID NOM STD",
    base."U/M",
    base."TRACABILITE LOTS",
    base."TRACABILITE LOTS_2",
    base."REGLE DE SERIE",
    base."REGLE DE SERIE_2",
    base."SUIVI DES SERIES",
    base."SUIVI DES SERIES_2",
    base."SUIVI SERIES APRES",
    base."SUIVI SERIES APRES_2",
    base."GP PRINCP ARTICLE",
    base."CONFIGURABLE",
    base."CONFIGURABLE_2",
    base."ID GARANTIE CLIENT",
    base."GARANTIE FOURNI.",
    base."AUTORISE CD COND",
    base."AUTORISE CD COND_2",
    base."REGLE SOUS-LOT",
    base."REGLE SOUS-LOT_2",
    base."REGLE DU LOT",
    base."REGLE DU LOT_2",
    base."ARTICLE POSITION",
    base."ARTICLE POSITION_2",
    base."ENTREE ID GP U/M",
    base."U/M CAP. ACTIVE E",
    base."U/M CAP. ACTIVE E_2",
    base."TRACAB. MULT NIV.",
    base."TRACAB. MULT NIV._2",
    base."REGLE LOT COMPOS.",
    base."REGLE LOT COMPOS._2",
    base."ARR.BC NUM SORTIS",
    base."ARR.BC NUM SORTIS_2",
    base."POIDS NET",
    base."U/M POIDS",
    base."VOLUME NET",
    base."U/M VOLUME",
    base."FACTEUR CHARGEMENT",
    base."AUTOR. NON CONSOM.",
    base."AUTOR. NON CONSOM._2",
    base."RECEPT./SORTIE",
    base."RECEPT./SORTIE_2",
    base."AR.CREA.SERIE RMA",
    base."AR.CREA.SERIE RMA_2",
    base."N.DESSIN TECHN.",
    base."CLASSIF TYPE PROD.",
    base."CLASSIF TYPE PROD._2",
    base."CODE CEST",
    base."CODE FCI",
    base.radical_article
   FROM base
  ORDER BY base.radical_article, (NULLIF(TRIM(BOTH FROM base."NORME CHARGE"), ''::text) IS NOT NULL) DESC, (length(TRIM(BOTH FROM base."N. ARTICLE"))), (TRIM(BOTH FROM base."N. ARTICLE"));;
