-- Genere par spec2catalog.py depuis Lot09_Projet_ParametresDeConfiguration_V3_0.xlsx / feuille PROJECT
CREATE TABLE IF NOT EXISTS clean_data.project (
    project_id                       VARCHAR(10),
    name                             VARCHAR(35),
    description                      VARCHAR(2000),
    plan_start                       DATE,
    plan_finish                      DATE,
    actual_start                     DATE,
    actual_finish                    DATE,
    frozen_date                      DATE,
    close_date                       DATE,
    cancel_date                      DATE,
    approved_date                    DATE,
    manager                          VARCHAR(20),
    customer_id                      VARCHAR(20),
    customer_responsible             VARCHAR(35),
    customer_project_id              VARCHAR(200),
    company                          VARCHAR(20),
    branch                           VARCHAR(20),
    calendar_id                      VARCHAR(10),
    program_id                       VARCHAR(10),
    planned_revenue                  NUMERIC(20,0),
    planned_cost                     NUMERIC(20,0),
    currency_type                    VARCHAR(10),
    probability_to_win               NUMERIC(20,0),
    default_char_temp                VARCHAR(10),
    access_on_off                    NUMERIC(20,0),
    date_created                     DATE,
    created_by                       VARCHAR(35),
    date_modified                    DATE,
    modified_by                      VARCHAR(35),
    baseline_revision_number         VARCHAR(40),
    earned_value_method              VARCHAR(4000),
    earned_value_method_db           VARCHAR(20),
    material_allocation              VARCHAR(4000),
    material_allocation_db           VARCHAR(25),
    financially_responsible          VARCHAR(20),
    budget_control_on                VARCHAR(4000),
    budget_control_on_db             VARCHAR(20),
    control_as_budgeted              VARCHAR(4000),
    control_as_budgeted_db           VARCHAR(20),
    control_on_total_budget          VARCHAR(4000),
    control_on_total_budget_db       VARCHAR(20),
    proj_unique_purchase             VARCHAR(4000),
    proj_unique_purchase_db          VARCHAR(5),
    proj_unique_sale                 VARCHAR(4000),
    proj_unique_sale_db              VARCHAR(5),
    copied_project                   VARCHAR(10),
    cost_structure_id                VARCHAR(20),
    multi_currency_budgeting         VARCHAR(4000),
    multi_currency_budgeting_db      VARCHAR(5),
    project_currency_type            VARCHAR(10),
    budget_currency_type             VARCHAR(10),
    project_currency_code            VARCHAR(3),
    category1_id                     VARCHAR(10),
    category2_id                     VARCHAR(10),
    validate_remaining_against       VARCHAR(4000),
    validate_remaining_against_db    VARCHAR(20),
    project_misc_comp_method         VARCHAR(4000),
    project_misc_comp_method_db      VARCHAR(20),
    internal_rental_price_list       VARCHAR(30),
    plan_project_transaction         VARCHAR(4000),
    plan_project_transaction_db      VARCHAR(20),
    work_day_to_hours_conv           NUMERIC(20,0),
    default_cost_activity_seq        NUMERIC(20,0),
    exclude_from_batch_invoice       VARCHAR(4000),
    exclude_from_batch_invoice_db    VARCHAR(20),
    activity_seq                     NUMERIC(20,0),
    mandatory_invoice_comment        VARCHAR(4000),
    mandatory_invoice_comment_db     VARCHAR(5),
    cash_forecast_multi_curr         VARCHAR(4000),
    cash_forecast_multi_curr_db      VARCHAR(5),
    business_transaction_id          VARCHAR(20)
    -- site                          VARCHAR(4000)  -- IN_SCOPE=NO
    -- budget_forecast_id            NUMERIC(20,0)  -- IN_SCOPE=NO
    -- selected_forecast_id          NUMERIC(20,0)  -- IN_SCOPE=NO
    -- selected_forecast_type        VARCHAR(4000)  -- IN_SCOPE=NO
    -- selected_forecast_version     VARCHAR(4000)  -- IN_SCOPE=NO
    -- financial_project_exist       VARCHAR(4000)  -- IN_SCOPE=NO
    -- cl_investment_code            VARCHAR(200)  -- IN_SCOPE=NO
    -- state                         VARCHAR(4000)  -- IN_SCOPE=NO
    -- objversion                    VARCHAR(14)  -- IN_SCOPE=NO
    -- objid                         VARCHAR(4000)  -- IN_SCOPE=NO
);
